import type { TriageRule } from "../types";

export const triageRules: TriageRule[] = [
  {
    id: "dolor-pecho",
    terms: ["dolor de pecho", "pecho opresivo", "opresión en el pecho", "opresion en el pecho", "dolor torácico", "dolor toracico"],
    signal: {
      id: "signal-dolor-pecho",
      label: "Posible señal de alarma cardiopulmonar",
      severity: "posible_emergencia",
      explanation: "El dolor u opresión en pecho puede requerir valoración presencial inmediata.",
    },
    action: {
      id: "action-atencion-inmediata",
      title: "Busca ayuda presencial inmediata",
      description: "Usa números oficiales de emergencia disponibles en tu localidad. La plataforma no contactó a ningún servicio externo.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "respiracion",
    terms: ["no puedo respirar", "dificultad para respirar", "falta de aire", "respira con dificultad"],
    signal: {
      id: "signal-respiracion",
      label: "Posible dificultad respiratoria",
      severity: "posible_emergencia",
      explanation: "La dificultad respiratoria intensa puede avanzar rápidamente y requiere atención profesional urgente.",
    },
    action: {
      id: "action-respiracion",
      title: "Prioriza atención urgente",
      description: "Permanece acompañado si es posible y busca ayuda presencial inmediata. No se activó ningún servicio desde este MVP.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "neurologico",
    terms: ["pérdida de conciencia", "perdida de conciencia", "desmayo", "convulsión", "convulsion", "debilidad de un lado", "confusión repentina", "confusion repentina", "no puede hablar"],
    signal: {
      id: "signal-neurologico",
      label: "Posible señal neurológica de alarma",
      severity: "posible_emergencia",
      explanation: "Cambios repentinos de conciencia, habla, fuerza o convulsiones ameritan valoración inmediata.",
    },
    action: {
      id: "action-neuro",
      title: "No esperes a que desaparezca",
      description: "Busca atención profesional de urgencia con los canales oficiales de tu localidad.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "sangrado-intenso",
    terms: ["sangrado abundante", "sangra mucho", "hemorragia", "sangrado que no para"],
    signal: {
      id: "signal-sangrado",
      label: "Posible sangrado abundante",
      severity: "posible_emergencia",
      explanation: "El sangrado abundante o que no se detiene puede requerir atención presencial inmediata.",
    },
    action: {
      id: "action-sangrado",
      title: "Busca atención urgente",
      description: "Acude a un servicio de urgencias o llama al 911 si existe peligro inmediato. La plataforma no realizó ninguna llamada.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "alergia-grave",
    terms: ["hinchazón en la cara", "hinchazon en la cara", "labios hinchados", "lengua hinchada", "ronchas y falta de aire", "alergia y no puedo respirar"],
    signal: {
      id: "signal-alergia-grave",
      label: "Posible reacción alérgica grave",
      severity: "posible_emergencia",
      explanation: "Inflamación facial, lengua hinchada o dificultad para respirar tras una reacción puede requerir urgencias.",
    },
    action: {
      id: "action-alergia-grave",
      title: "Valoración urgente",
      description: "Busca atención presencial inmediata o llama al 911 si hay dificultad para respirar. No se activó ningún servicio desde la plataforma.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "embarazo-alarma",
    terms: ["embarazo con sangrado", "embarazada y sangrado", "embarazo y dolor intenso", "embarazada y dolor fuerte"],
    signal: {
      id: "signal-embarazo",
      label: "Posible señal de alarma durante embarazo",
      severity: "posible_emergencia",
      explanation: "Sangrado o dolor intenso durante embarazo amerita valoración presencial urgente.",
    },
    action: {
      id: "action-embarazo",
      title: "Busca atención presencial inmediata",
      description: "Acude a urgencias o llama al 911 si existe peligro inmediato. Esta plataforma no contactó servicios externos.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "autolesion",
    terms: ["quiero hacerme daño", "quiero hacerme dano", "ideas de autolesión", "ideas de autolesion", "no quiero vivir"],
    signal: {
      id: "signal-autolesion",
      label: "Posible riesgo inmediato de autolesión",
      severity: "posible_emergencia",
      explanation: "Las ideas de autolesión requieren apoyo inmediato y acompañamiento presencial.",
    },
    action: {
      id: "action-autolesion",
      title: "Busca ayuda inmediata",
      description: "Busca compañía de una persona de confianza y llama al 911 o a servicios oficiales de emergencia de tu localidad.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "fiebre-rigidez",
    terms: ["fiebre con rigidez de cuello", "fiebre y cuello rígido", "fiebre y cuello rigido"],
    signal: {
      id: "signal-rigidez-cuello",
      label: "Fiebre con rigidez de cuello",
      severity: "posible_emergencia",
      explanation: "La fiebre con rigidez de cuello puede requerir valoración urgente.",
    },
    action: {
      id: "action-rigidez-cuello",
      title: "Prioriza urgencias",
      description: "Busca atención presencial inmediata. La orientación es informativa y no sustituye una valoración médica.",
      priority: "urgente",
      origin: "reglas_locales",
    },
  },
  {
    id: "fiebre-persistente",
    terms: ["fiebre alta", "fiebre persistente", "temperatura muy alta", "fiebre de varios días", "fiebre de varios dias"],
    signal: {
      id: "signal-fiebre",
      label: "Fiebre que requiere seguimiento",
      severity: "consulta_prioritaria",
      explanation: "La fiebre alta o persistente puede requerir consulta profesional, especialmente con otros síntomas.",
    },
    action: {
      id: "action-fiebre",
      title: "Prepara consulta prioritaria",
      description: "Registra temperatura, duración, síntomas asociados y antecedentes para compartirlos con personal de salud.",
      priority: "prioritaria",
      origin: "reglas_locales",
    },
  },
  {
    id: "deshidratacion",
    terms: ["vómito persistente", "vomito persistente", "diarrea intensa", "no retiene líquidos", "no retiene liquidos", "orina muy poco"],
    signal: {
      id: "signal-deshidratacion",
      label: "Posible riesgo de deshidratación",
      severity: "consulta_prioritaria",
      explanation: "Pérdida importante de líquidos o imposibilidad de retenerlos puede requerir valoración pronta.",
    },
    action: {
      id: "action-deshidratacion",
      title: "Monitorea líquidos y consulta",
      description: "Observa evolución y busca atención profesional si persiste o empeora. No se indican medicamentos ni dosis.",
      priority: "prioritaria",
      origin: "reglas_locales",
    },
  },
  {
    id: "deterioro-rapido",
    terms: ["empeora rápido", "empeora rapido", "deterioro rápido", "deterioro rapido", "cada vez peor"],
    signal: {
      id: "signal-deterioro",
      label: "Deterioro rápido declarado",
      severity: "consulta_prioritaria",
      explanation: "El empeoramiento rápido puede requerir valoración profesional el mismo día o en un plazo breve.",
    },
    action: {
      id: "action-deterioro",
      title: "Busca consulta prioritaria",
      description: "Solicita valoración profesional presencial o teleorientación profesional cuando esté disponible.",
      priority: "prioritaria",
      origin: "reglas_locales",
    },
  },
  {
    id: "seguimiento",
    terms: ["cansancio", "dolor de cabeza", "tos", "dolor muscular", "malestar", "mareo"],
    signal: {
      id: "signal-seguimiento",
      label: "Síntomas para seguimiento informado",
      severity: "seguimiento_recomendado",
      explanation: "Los síntomas declarados pueden organizarse para preparar una consulta si se requiere.",
    },
    action: {
      id: "action-seguimiento",
      title: "Registra evolución",
      description: "Anota inicio, cambios, intensidad, temperatura si aplica y factores que empeoran o mejoran.",
      priority: "pronta",
      origin: "reglas_locales",
    },
  },
];
