import type { PreguntaBanco, PreguntaBancoSinId } from "./types";

const preguntasEticasHistoricas: PreguntaBancoSinId[] = [
  { tipo: "etica", pregunta: "Si un integrante del comité descubre información técnicamente relevante obtenida de manera ilegal pero imposible de verificar por otra vía, ¿cuál es la decisión éticamente más sólida?", opciones: ["No utilizarla como evidencia principal y buscar corroboración verificable e independiente.", "Publicarla inmediatamente por interés público.", "Ocultarla completamente aunque revele daño estructural.", "Filtrarla anónimamente para evitar responsabilidad."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué principio debe prevalecer cuando existe tensión entre transparencia pública y protección de personas vulnerables?", opciones: ["Minimización de daño sin sacrificar trazabilidad institucional verificable.", "Transparencia absoluta sin restricciones.", "Confidencialidad total de cualquier información sensible.", "Publicar únicamente información autorizada por autoridades."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué constituye un conflicto de interés estructural dentro de un comité ciudadano experto?", opciones: ["Participar en decisiones donde existen beneficios directos, indirectos o relaciones relevantes no declaradas.", "Tener opiniones políticas personales.", "Haber trabajado previamente en el sector evaluado.", "Discrepar metodológicamente con otros expertos."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué criterio ético fortalece más la legitimidad de un dictamen ciudadano?", opciones: ["Metodología verificable, independencia y límites explícitos del análisis realizado.", "Consenso unánime dentro del comité.", "Aprobación pública mayoritaria.", "Difusión masiva en medios y redes."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "Si un experto detecta un error metodológico que favorece ideológicamente su posición personal, ¿qué debe hacer?", opciones: ["Reportarlo y corregirlo aunque afecte la conclusión deseada.", "Mantenerlo si el objetivo final es socialmente positivo.", "Esperar a que otro integrante lo detecte.", "Modificar únicamente la redacción final del informe."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético surge cuando un comité confunde evidencia con activismo?", opciones: ["Debilitar credibilidad técnica y convertir el análisis en una postura previamente decidida.", "Reducir velocidad de deliberación.", "Eliminar participación ciudadana.", "Impedir análisis interdisciplinario."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué práctica protege mejor la imparcialidad deliberativa?", opciones: ["Separar hipótesis, evidencia, interpretación y recomendación de manera explícita.", "Evitar completamente opiniones divergentes.", "Limitar participación de expertos externos.", "Usar solo fuentes institucionales oficiales."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué constituye una manipulación ética de datos aunque las cifras sean reales?", opciones: ["Presentar información fuera de contexto para inducir conclusiones engañosas.", "Usar visualizaciones complejas.", "Incluir márgenes de error estadísticos.", "Comparar series históricas diferentes."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué obligación ética tiene un comité ante incertidumbre técnica significativa?", opciones: ["Explicitar límites metodológicos y evitar afirmaciones concluyentes no sustentadas.", "Suspender cualquier publicación pública.", "Delegar la decisión a autoridades externas.", "Simplificar resultados para evitar confusión."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué criterio ético debe aplicarse al uso de inteligencia artificial en dictámenes ciudadanos?", opciones: ["La IA debe asistir análisis verificables sin sustituir responsabilidad humana deliberativa.", "La IA debe maximizar eficiencia sobre transparencia.", "La IA debe tomar decisiones neutrales automáticamente.", "La IA debe reemplazar evaluaciones humanas subjetivas."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético implica publicar denuncias no corroboradas con identificación personal?", opciones: ["Exponer personas a daño irreversible sin debido estándar de verificación.", "Reducir velocidad de investigación.", "Eliminar trazabilidad documental.", "Impedir participación ciudadana futura."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué práctica fortalece más la independencia de un comité?", opciones: ["Diversidad metodológica y separación de intereses políticos, económicos y operativos.", "Rotación constante de integrantes.", "Aprobación institucional gubernamental.", "Uniformidad ideológica entre expertos."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué obligación ética existe al usar testimonios de víctimas o denunciantes?", opciones: ["Proteger identidad, consentimiento y contexto evitando revictimización.", "Publicar íntegramente testimonios para transparencia.", "Eliminar cualquier referencia emocional.", "Usar únicamente testimonios judicializados."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué constituye una deliberación ética técnicamente válida?", opciones: ["Evaluar argumentos y evidencia aunque contradigan preferencias previas del comité.", "Mantener coherencia ideológica permanente.", "Evitar desacuerdos para preservar legitimidad.", "Priorizar posiciones mayoritarias automáticamente."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo surge cuando un comité depende financieramente del actor evaluado?", opciones: ["Comprometer independencia real y percepción pública de imparcialidad.", "Reducir acceso a información técnica.", "Eliminar trazabilidad de resultados.", "Impedir análisis interdisciplinario."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué principio ético debe prevalecer frente a presión política externa?", opciones: ["Integridad metodológica y fidelidad a evidencia verificable.", "Neutralidad discursiva absoluta.", "Evitar cualquier conclusión controversial.", "Posponer indefinidamente el dictamen."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué hace éticamente válida una alerta pública preventiva?", opciones: ["Basarse en evidencia razonable y proporcionalidad frente al riesgo potencial.", "Generar máxima atención mediática.", "Publicarse únicamente tras unanimidad total.", "Usar lenguaje alarmista para acelerar reacción."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético existe al simplificar excesivamente problemas complejos?", opciones: ["Ocultar variables críticas y favorecer decisiones erróneas o manipulables.", "Reducir interés ciudadano.", "Eliminar necesidad de expertos.", "Impedir comunicación pública efectiva."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué práctica protege mejor la memoria institucional de los comités?", opciones: ["Documentar criterios, cambios metodológicos y fundamentos deliberativos verificables.", "Rotar completamente integrantes cada ciclo.", "Eliminar versiones preliminares de análisis.", "Centralizar decisiones en coordinadores técnicos."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué obligación ética existe ante errores detectados en dictámenes previos?", opciones: ["Corregir públicamente preservando trazabilidad histórica de cambios y razones.", "Eliminar versiones antiguas para evitar confusión.", "Esperar confirmación institucional externa.", "Corregir solo errores con impacto político."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué constituye captura institucional de un comité?", opciones: ["Cuando intereses externos condicionan metodología, prioridades o conclusiones sustantivas.", "Recibir críticas públicas frecuentes.", "Mantener relaciones con universidades.", "Publicar dictámenes controversiales."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué criterio ético fortalece más la participación ciudadana?", opciones: ["Permitir intervención significativa sin sacrificar rigor metodológico y protección de evidencia.", "Aceptar cualquier aportación sin filtros.", "Delegar decisiones técnicas a votación popular.", "Limitar participación a especialistas acreditados."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético implica usar métricas técnicamente correctas pero socialmente engañosas?", opciones: ["Generar conclusiones aparentemente objetivas que distorsionan realidad sustantiva.", "Reducir precisión estadística.", "Eliminar interoperabilidad de datos.", "Impedir análisis comparativo internacional."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué práctica fortalece más la justicia procedimental dentro de un comité?", opciones: ["Garantizar revisión crítica, trazabilidad y posibilidad razonada de disenso.", "Mantener votaciones secretas permanentes.", "Evitar participación interdisciplinaria.", "Centralizar validación metodológica."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué obligación ética existe respecto a sesgos algorítmicos detectados?", opciones: ["Documentarlos, mitigarlos y transparentar sus posibles efectos en resultados.", "Ocultarlos para evitar desconfianza pública.", "Eliminar automáticamente cualquier modelo automatizado.", "Delegar toda responsabilidad al desarrollador original."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético surge cuando la reputación de expertos pesa más que la evidencia?", opciones: ["Convertir autoridad percibida en sustituto de validación metodológica.", "Reducir eficiencia deliberativa.", "Eliminar necesidad de documentación técnica.", "Impedir participación ciudadana general."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué criterio ético debe aplicarse ante información técnicamente ambigua pero políticamente explosiva?", opciones: ["Evaluar proporcionalidad, verificabilidad y potencial de daño antes de difundirla.", "Publicarla inmediatamente por transparencia radical.", "Reservarla indefinidamente aunque exista riesgo público.", "Delegar decisión a actores políticos externos."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué práctica protege mejor legitimidad democrática de los comités?", opciones: ["Mantener independencia, transparencia metodológica y límites claros de competencia.", "Buscar aprobación constante de autoridades.", "Evitar cualquier posicionamiento técnico controversial.", "Limitar deliberaciones al ámbito interno."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Qué riesgo ético existe cuando la velocidad de publicación desplaza la validación rigurosa?", opciones: ["Normalizar errores, amplificar desinformación y erosionar confianza institucional.", "Reducir participación ciudadana activa.", "Eliminar necesidad de trazabilidad.", "Impedir análisis interdisciplinario."], respuestaCorrecta: 0 },
  { tipo: "etica", pregunta: "¿Cuál es el principio rector ético de los Comités Ciudadanos Expertos?", opciones: ["La legitimidad pública surge de evidencia verificable, independencia y responsabilidad metodológica.", "La neutralidad absoluta garantiza objetividad total.", "La mayoría ciudadana define automáticamente la verdad.", "La tecnología puede sustituir deliberación ética humana."], respuestaCorrecta: 0 },
];

export const preguntasEticasGlobales: PreguntaBanco[] = preguntasEticasHistoricas.map(
  (pregunta, index) => ({
    ...pregunta,
    id: `etica-${String(index + 1).padStart(3, "0")}`,
  }),
);
