import type { SearchCaseDataset } from "./types";

export const demoDataset: SearchCaseDataset = {
  cases: [
    {
      id: "case-tam-001",
      folio: "TP-M5-2026-001",
      protectedName: false,
      personName: "Mariana Lopez Rivera",
      displayName: "Mariana Lopez Rivera",
      age: 24,
      gender: "Mujer",
      status: "active",
      priority: "critical",
      privacyLevel: "committee_shared",
      state: "Tamaulipas",
      municipality: "Reynosa",
      collective: "Colectivo Familias en Busqueda Norte",
      committeeId: "committee-forensic-north",
      summary: "Expediente con seguimiento activo, testimonios vecinales y solicitud de revision tecnica ciudadana.",
      narrative:
        "La familia reporta ausencia posterior a una salida laboral. Existen mensajes previos, una ruta aproximada y dos testimonios que requieren organizacion documental y seguimiento prudente.",
      lastSeenDate: "2026-05-14",
      lastSeenPlace: "Colonia Longoria, Reynosa",
      createdAt: "2026-05-16T15:20:00.000Z",
      updatedAt: "2026-07-06T18:40:00.000Z",
      tags: ["salida de trabajo", "testimonio", "transporte"],
      relatedCaseIds: ["case-gto-002"],
    },
    {
      id: "case-gto-002",
      folio: "TP-M5-2026-002",
      protectedName: true,
      personName: "Nombre protegido",
      displayName: "Persona con nombre protegido",
      age: 31,
      gender: "Hombre",
      status: "committee_review",
      priority: "high",
      privacyLevel: "collective_shared",
      state: "Guanajuato",
      municipality: "Celaya",
      collective: "Red de Acompanamiento Bajio",
      committeeId: "committee-context-bajio",
      summary: "Caso con indicios de ruta compartida y observaciones del comite ciudadano.",
      narrative:
        "La familia solicita acompanamiento para ordenar gestiones, llamadas, ubicaciones aproximadas y oficios recibidos. La narrativa contiene fechas verificables por la familia.",
      lastSeenDate: "2026-04-21",
      lastSeenPlace: "Terminal de autobuses de Celaya",
      createdAt: "2026-04-23T10:15:00.000Z",
      updatedAt: "2026-07-02T13:10:00.000Z",
      tags: ["transporte", "comunicacion", "gestion institucional"],
      relatedCaseIds: ["case-tam-001"],
    },
    {
      id: "case-ver-003",
      folio: "TP-M5-2026-003",
      protectedName: false,
      personName: "Sofia Hernandez Cruz",
      displayName: "Sofia Hernandez Cruz",
      age: 19,
      gender: "Mujer",
      status: "institutional_followup",
      priority: "medium",
      privacyLevel: "family_private",
      state: "Veracruz",
      municipality: "Xalapa",
      collective: "Familia acompanada",
      committeeId: null,
      summary: "Seguimiento de solicitudes documentales y preparacion de constancia civica imprimible.",
      narrative:
        "La familia conserva capturas, horarios y una lista de personas contactadas. El expediente se mantiene privado mientras se completa la revision familiar.",
      lastSeenDate: "2026-06-03",
      lastSeenPlace: "Zona centro de Xalapa",
      createdAt: "2026-06-04T09:30:00.000Z",
      updatedAt: "2026-06-29T20:15:00.000Z",
      tags: ["capturas", "seguimiento familiar"],
      relatedCaseIds: [],
    },
    {
      id: "case-jal-004",
      folio: "TP-M5-2026-004",
      protectedName: true,
      personName: "Nombre protegido",
      displayName: "Persona adolescente con nombre protegido",
      age: 16,
      gender: "No publicado",
      status: "draft",
      priority: "high",
      privacyLevel: "family_private",
      state: "Jalisco",
      municipality: "Tlajomulco de Zuniga",
      collective: "Borrador familiar",
      committeeId: null,
      summary: "Borrador inicial con datos sensibles protegidos y narrativa incompleta.",
      narrative:
        "Registro familiar en preparacion. Faltan datos de contacto, ultima hora conocida y revision de privacidad por seccion.",
      lastSeenDate: "2026-07-01",
      lastSeenPlace: "Municipio de Tlajomulco de Zuniga",
      createdAt: "2026-07-02T17:45:00.000Z",
      updatedAt: "2026-07-05T11:05:00.000Z",
      tags: ["borrador", "privacidad alta"],
      relatedCaseIds: [],
    },
  ],
  events: [
    {
      id: "event-001",
      caseId: "case-tam-001",
      type: "report",
      title: "Registro inicial familiar",
      description: "Se capturaron datos basicos, ultima ubicacion aproximada y contacto de seguimiento.",
      occurredAt: "2026-05-16T15:20:00.000Z",
      actorRole: "Familia",
      privacyLevel: "family_private",
      relatedEvidenceIds: [],
    },
    {
      id: "event-002",
      caseId: "case-tam-001",
      type: "evidence",
      title: "Capturas agregadas",
      description: "Se incorporaron capturas de conversacion y contexto de fuente.",
      occurredAt: "2026-05-17T19:10:00.000Z",
      actorRole: "Colectivo",
      privacyLevel: "collective_shared",
      relatedEvidenceIds: ["evidence-001"],
    },
    {
      id: "event-003",
      caseId: "case-tam-001",
      type: "committee",
      title: "Solicitud de revision ciudadana",
      description: "El comite revisa consistencia narrativa, privacidad y pendientes de seguimiento.",
      occurredAt: "2026-06-02T12:00:00.000Z",
      actorRole: "Acompanamiento civico",
      privacyLevel: "committee_shared",
      relatedEvidenceIds: ["evidence-001", "evidence-002"],
    },
    {
      id: "event-004",
      caseId: "case-gto-002",
      type: "institutional_action",
      title: "Gestion documental registrada",
      description: "Se registro folio externo aportado por la familia y proximo paso de seguimiento.",
      occurredAt: "2026-04-25T16:00:00.000Z",
      actorRole: "Familia",
      privacyLevel: "collective_shared",
      relatedEvidenceIds: ["evidence-003"],
    },
    {
      id: "event-005",
      caseId: "case-ver-003",
      type: "privacy",
      title: "Privacidad reforzada",
      description: "Se limito visibilidad a privado familiar mientras se depuran datos sensibles.",
      occurredAt: "2026-06-10T08:30:00.000Z",
      actorRole: "Familia",
      privacyLevel: "family_private",
      relatedEvidenceIds: [],
    },
  ],
  evidence: [
    {
      id: "evidence-001",
      caseId: "case-tam-001",
      name: "capturas-mensajes.pdf",
      category: "message",
      fileType: "application/pdf",
      sizeBytes: 1240000,
      addedAt: "2026-05-17T19:10:00.000Z",
      privacyLevel: "collective_shared",
      reviewStatus: "in_analysis",
      localStatus: "Metadata demostrativa; archivo no subido",
      hash: "3b6f7c0c7f5c8d9eae4f79e4a5a20a8a819cc9fba83cb929a5f1e2f78971b671",
      note: "Pendiente de procesamiento seguro por servicio futuro.",
    },
    {
      id: "evidence-002",
      caseId: "case-tam-001",
      name: "croquis-ruta-aproximada.png",
      category: "location_context",
      fileType: "image/png",
      sizeBytes: 640000,
      addedAt: "2026-05-21T11:25:00.000Z",
      privacyLevel: "committee_shared",
      reviewStatus: "pending",
      localStatus: "Archivo seleccionado localmente",
      note: "La sanitizacion real requerira el servicio de procesamiento.",
    },
    {
      id: "evidence-003",
      caseId: "case-gto-002",
      name: "oficio-recibido-familia.pdf",
      category: "document",
      fileType: "application/pdf",
      sizeBytes: 820000,
      addedAt: "2026-04-25T16:00:00.000Z",
      privacyLevel: "collective_shared",
      reviewStatus: "observations",
      localStatus: "Metadata demostrativa; archivo no subido",
      hash: "df7b790f6c6f64f6b9416f5404f5dfd784b1c069d8b17481b724fb4c39817d8e",
      note: "Revisar legibilidad antes de compartir con comite.",
    },
  ],
  institutionalActions: [
    {
      id: "action-001",
      caseId: "case-tam-001",
      institution: "Comision local de busqueda",
      actionType: "Solicitud de informacion",
      folioExternal: "CLB-TAM-2451",
      requestedAt: "2026-05-18T09:00:00.000Z",
      status: "needs_follow_up",
      nextStep: "Preparar recordatorio documentado y anexar cronologia familiar.",
    },
    {
      id: "action-002",
      caseId: "case-gto-002",
      institution: "Area de atencion a familias",
      actionType: "Seguimiento de cita",
      folioExternal: "ATF-GTO-1109",
      requestedAt: "2026-05-03T13:00:00.000Z",
      status: "in_progress",
      nextStep: "Confirmar acuse recibido y registrar respuesta.",
    },
    {
      id: "action-003",
      caseId: "case-ver-003",
      institution: "Archivo familiar",
      actionType: "Orden documental interno",
      requestedAt: "2026-06-12T18:40:00.000Z",
      status: "responded",
      nextStep: "Generar documento civico de apoyo para revision familiar.",
    },
  ],
  committees: [
    {
      id: "committee-forensic-north",
      name: "Comite Ciudadano de Documentacion Norte",
      specialty: "Cronologia, indicios y privacidad",
      territory: "Tamaulipas y Nuevo Leon",
      level: "regional",
      availability: "available",
      caseCount: 8,
      verificationLabel: "Verificacion demostrativa de perfil",
    },
    {
      id: "committee-context-bajio",
      name: "Mesa Tecnica Ciudadana Bajio",
      specialty: "Contexto territorial y seguimiento",
      territory: "Guanajuato, Queretaro y Michoacan",
      level: "regional",
      availability: "limited",
      caseCount: 5,
      verificationLabel: "Validacion interna demostrativa",
    },
    {
      id: "committee-documents",
      name: "Red de Revision Documental Humanitaria",
      specialty: "Documentos, versiones y lenguaje claro",
      territory: "Nacional",
      level: "national",
      availability: "available",
      caseCount: 12,
      verificationLabel: "Perfil ciudadano revisado en entorno de prueba",
    },
  ],
  reviews: [
    {
      id: "review-001",
      caseId: "case-tam-001",
      committeeId: "committee-forensic-north",
      status: "in_analysis",
      requestedAt: "2026-06-02T12:00:00.000Z",
      updatedAt: "2026-07-06T18:40:00.000Z",
      summary: "Revision de consistencia de timeline, privacidad de evidencias y siguientes gestiones.",
      observations: ["Separar datos publicos y datos de contacto.", "Completar fuente de dos testimonios."],
    },
    {
      id: "review-002",
      caseId: "case-gto-002",
      committeeId: "committee-context-bajio",
      status: "observations",
      requestedAt: "2026-05-10T10:00:00.000Z",
      updatedAt: "2026-06-28T15:35:00.000Z",
      summary: "El comite ciudadano pide ordenar fechas de llamadas y transporte.",
      observations: ["Agregar hora aproximada de ultima llamada.", "Marcar documento externo como privado."],
    },
  ],
  geneticReferences: [
    {
      id: "gen-001",
      caseId: "case-tam-001",
      referenceType: "Muestra familiar referida por institucion",
      relationship: "Madre",
      originInstitution: "Laboratorio externo indicado por la familia",
      externalFolio: "LAB-REF-7742",
      registeredAt: "2026-05-29T09:10:00.000Z",
      consentStatus: "signed",
      requestStatus: "comparison_requested",
      custodyInstitution: "Institucion de resguardo informada por la familia",
      linkedDocumentIds: ["doc-001"],
      followUp: "Registrar acuse y proxima fecha de respuesta. Sin calculos de compatibilidad en la plataforma.",
    },
    {
      id: "gen-002",
      caseId: "case-gto-002",
      referenceType: "Solicitud de comparacion documental",
      relationship: "Hermana",
      originInstitution: "Area de atencion a familias",
      externalFolio: "SOL-GEN-2190",
      registeredAt: "2026-06-18T11:45:00.000Z",
      consentStatus: "pending",
      requestStatus: "consent_pending",
      custodyInstitution: "Pendiente de confirmar",
      linkedDocumentIds: [],
      followUp: "No solicitar secuencias ni porcentajes. Solo documentar estado de solicitud.",
    },
  ],
  documents: [
    {
      id: "doc-001",
      caseId: "case-tam-001",
      title: "Expediente civico de apoyo",
      version: "1.3",
      generatedAt: "2026-07-06T18:42:00.000Z",
      status: "ready",
      technicalHash: "7f82e23be639f24587188d12a91b8ad4fc58117656b51c97a4f4087fd45bbd16",
    },
    {
      id: "doc-002",
      caseId: "case-gto-002",
      title: "Resumen para revision ciudadana",
      version: "0.9",
      generatedAt: "2026-06-28T15:40:00.000Z",
      status: "draft",
      technicalHash: "0cf5a81e4d6ca87ed7f7bbbf6a54c79a0c1462c08a73a11a4d2118f7e4df7b90",
    },
  ],
  auditEvents: [
    {
      id: "audit-001",
      occurredAt: "2026-07-06T18:42:00.000Z",
      actorRole: "Acompanamiento civico",
      action: "Documento generado",
      resource: "doc-001",
      version: "1.3",
      caseId: "case-tam-001",
      hash: "7f82e23be639f24587188d12a91b8ad4fc58117656b51c97a4f4087fd45bbd16",
      status: "completed",
    },
    {
      id: "audit-002",
      occurredAt: "2026-07-02T13:10:00.000Z",
      actorRole: "Comite ciudadano",
      action: "Observaciones agregadas",
      resource: "review-002",
      version: "0.9",
      caseId: "case-gto-002",
      status: "recorded",
    },
    {
      id: "audit-003",
      occurredAt: "2026-07-05T11:05:00.000Z",
      actorRole: "Familia",
      action: "Privacidad revisada",
      resource: "case-jal-004",
      version: "0.1",
      caseId: "case-jal-004",
      status: "recorded",
    },
  ],
  versions: [
    {
      id: "version-001",
      caseId: "case-tam-001",
      version: "1.0",
      createdAt: "2026-05-16T15:20:00.000Z",
      actorRole: "Familia",
      summary: "Registro inicial del expediente.",
    },
    {
      id: "version-002",
      caseId: "case-tam-001",
      version: "1.3",
      createdAt: "2026-07-06T18:42:00.000Z",
      actorRole: "Acompanamiento civico",
      summary: "Se integraron evidencias, revision de comite y documento imprimible.",
      hash: "7f82e23be639f24587188d12a91b8ad4fc58117656b51c97a4f4087fd45bbd16",
    },
    {
      id: "version-003",
      caseId: "case-gto-002",
      version: "0.9",
      createdAt: "2026-06-28T15:40:00.000Z",
      actorRole: "Comite ciudadano",
      summary: "Observaciones sobre cronologia y documento externo.",
      hash: "0cf5a81e4d6ca87ed7f7bbbf6a54c79a0c1462c08a73a11a4d2118f7e4df7b90",
    },
  ],
  alerts: [
    {
      id: "alert-001",
      caseId: "case-tam-001",
      severity: "urgent",
      title: "Seguimiento pendiente",
      description: "Hay una gestion con proximo paso vencido en el expediente demostrativo.",
      createdAt: "2026-07-07T09:00:00.000Z",
      status: "open",
    },
    {
      id: "alert-002",
      caseId: "case-jal-004",
      severity: "warning",
      title: "Borrador incompleto",
      description: "Faltan datos minimos antes de compartir con colectivo o comite.",
      createdAt: "2026-07-05T11:05:00.000Z",
      status: "acknowledged",
    },
    {
      id: "alert-003",
      severity: "info",
      title: "Datos demostrativos del entorno de prueba",
      description: "Las metricas del panel se calculan solo con expedientes mock incluidos en este modulo.",
      createdAt: "2026-07-01T08:00:00.000Z",
      status: "open",
    },
  ],
};
