export const modulosTecnocracia = [
  { id: 1, nombre: "Seguridad Ciudadana (Cero Corrupción)" },
  { id: 2, nombre: "Fiscalía Forense Ciudadana con IA" },
  { id: 3, nombre: "Congreso Cívico de Evaluación Legislativa" },
  { id: 4, nombre: "Derechos Humanos y Contrapeso Institucional" },
  { id: 5, nombre: "Madres Buscadoras y Búsqueda Forense" },
  { id: 6, nombre: "Sistema Judicial de Carrera" },
  { id: 7, nombre: "Tribunales de Alta Integridad" },
  { id: 8, nombre: "Auditoría Cívica de Gobiernos Estatales y Municipales" },
  { id: 9, nombre: "Ética Pública, Conflictos de Interés y Puertas Giratorias" },
  { id: 10, nombre: "Salud y Bienestar Digital" },
  { id: 11, nombre: "Educación y Capacitación Funcional" },
  { id: 12, nombre: "Infraestructura, Vivienda y Mantenimiento Predictivo" },
  { id: 13, nombre: "Movilidad, Transporte y Derecho a la Ciudad" },
  { id: 14, nombre: "Sistema DIF Cívico y Protección Social" },
  { id: 15, nombre: "Juventud, Futuro, Deporte y Protección Intergeneracional" },
  { id: 16, nombre: "Artes, Cultura, Patrimonio Vivo y Turismo Comunitario" },
  { id: 17, nombre: "Economía Regional e Inversión Cívica" },
  { id: 18, nombre: "Soberanía Energética y Recursos Estratégicos" },
  { id: 19, nombre: "Licitaciones Éticas y Fomento a MiPyMEs" },
  { id: 20, nombre: "Ciencia, Tecnología e Innovación Pública" },
  { id: 21, nombre: "INE Cívico y Observación Electoral Permanente" },
  { id: 22, nombre: "Anticorrupción e Inteligencia Financiera" },
  { id: 23, nombre: "Auditoría de Sistemas y Guardián del Código" },
  { id: 24, nombre: "Observatorio de Prensa Libre y Verdad Pública" },
  { id: 25, nombre: "Verdad Histórica, Memoria y No Repetición" },
  { id: 26, nombre: "Agricultura, Campo, Pesca y Soberanía Alimentaria" },
  { id: 27, nombre: "Agua, Territorio y Soberanía Hídrica" },
  { id: 28, nombre: "Medio Ambiente, Cambio Climático y Sustentabilidad Intergeneracional" },
  { id: 29, nombre: "Emergencias, Protección Civil y Resiliencia" },
  { id: 30, nombre: "Relaciones Internacionales, Derechos Humanos y Diáspora" },
];
