import type { ElectionRecord } from "./types";

export const DEMO_RECORDS: ElectionRecord[] = [
  {
    id: "demo-1",
    folio: "OEC-2026-0001",
    createdAt: "2026-06-07T18:32:15.000Z",
    version: 1,
    process: "2026",
    electionType: "Ayuntamiento",
    state: "Jalisco",
    district: "12",
    municipality: "Guadalajara",
    section: "0912",
    pollingPlace: "Básica",
    votesA: 180,
    votesB: 96,
    votesC: 12,
    unregistered: 0,
    nullVotes: 7,
    declaredTotal: 295,
    nominalList: 650,
    notes: "Captura demostrativa a partir de una sábana pública ficticia.",
    incident: "",
    alerts: [],
    status: "sin_hallazgos",
    history: [
      { at: "2026-06-07T18:32:15.000Z", status: "pendiente", note: "Registro local creado" },
      { at: "2026-06-08T10:05:00.000Z", status: "sin_hallazgos", note: "Revisión demostrativa" },
    ],
    demo: true,
  },
  {
    id: "demo-2",
    folio: "OEC-2026-0002",
    createdAt: "2026-06-07T19:10:42.000Z",
    version: 1,
    process: "2026",
    electionType: "Diputación local",
    state: "Guerrero",
    district: "02",
    municipality: "Chilpancingo",
    section: "4051",
    pollingPlace: "Contigua 1",
    votesA: 120,
    votesB: 5,
    votesC: 0,
    unregistered: 0,
    nullVotes: 0,
    declaredTotal: 125,
    nominalList: 500,
    notes: "Ejemplo para explicar una concentración estadística.",
    incident: "Faltó información contextual en la captura.",
    alerts: ["CONCENTRACION_ALTA"],
    status: "analisis",
    history: [
      { at: "2026-06-07T19:10:42.000Z", status: "pendiente", note: "Registro local creado" },
      { at: "2026-06-08T12:00:00.000Z", status: "analisis", note: "Turno demostrativo a mesa técnica" },
    ],
    demo: true,
  },
];
