"use client";

import { useState } from "react";
import { Notice, Panel } from "./ModuleChrome";
import { formatBytes, sha256 } from "@/lib/relaciones-internacionales/utils";
import type { EvidenceItem } from "@/lib/relaciones-internacionales/types";

const input = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:border-[#E4007C] focus:outline-none focus:ring-2 focus:ring-pink-100";
const criteria = ["Idoneidad técnica","Experiencia diplomática","Protección consular","Derechos humanos","Cooperación internacional","Atención a la diáspora","Transparencia","Posibles conflictos de interés","Impacto reputacional","Congruencia con compromisos internacionales"];

export function DiplomaticEvaluation() {
  const [form,setForm]=useState({country:"",mission:"",kind:"Embajada",criterion:"Idoneidad técnica",period:"",contribution:"",sources:"",notes:""});
  const [evidence,setEvidence]=useState<EvidenceItem[]>([]); const [errors,setErrors]=useState<string[]>([]); const [report,setReport]=useState<{folio:string;hash:string}|null>(null); const [message,setMessage]=useState("");
  const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  function addFiles(files: FileList|null) { if(!files)return; const allowed=["application/pdf","image/png","image/jpeg","text/plain"]; const next:EvidenceItem[]=[]; const issues:string[]=[]; Array.from(files).forEach(file=>{ if(!allowed.includes(file.type)) issues.push(`${file.name}: formato no permitido.`); else if(file.size>5*1024*1024) issues.push(`${file.name}: supera 5 MB.`); else next.push({id:crypto.randomUUID(),name:file.name,type:file.type,size:file.size,addedAt:new Date().toLocaleString("es-MX")}); }); setEvidence(current=>[...current,...next]); setErrors(issues); }
  async function generate() { const issues=[]; if(!form.country.trim())issues.push("Indique el país receptor."); if(!form.mission.trim())issues.push("Indique la misión diplomática."); if(!form.period)issues.push("Indique el periodo evaluado."); if(form.contribution.trim().length<80)issues.push("La aportación debe contener al menos 80 caracteres."); if(!form.sources.trim())issues.push("Agregue al menos una fuente pública."); setErrors(issues); if(issues.length)return; const folio=`M30-EVAL-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`; const hash=await sha256(JSON.stringify({folio,form,evidence,version:"1.0"})); setReport({folio,hash}); setMessage("Borrador cívico generado localmente."); }
  function clear(){ if(!window.confirm("¿Borrar el formulario y sus evidencias locales?"))return; setForm({country:"",mission:"",kind:"Embajada",criterion:"Idoneidad técnica",period:"",contribution:"",sources:"",notes:""});setEvidence([]);setReport(null);setErrors([]); }
  return <div className="space-y-5"><Panel title="Evaluación Cívica de Representación Diplomática" description="Dictaminación ciudadana y técnica sobre idoneidad, trayectoria, congruencia institucional y desempeño público de embajadas, consulados y misiones mexicanas.">
    <Notice tone="amber">Herramienta de evaluación ciudadana. No constituye una resolución oficial ni interviene en las facultades constitucionales de nombramiento y conducción de la política exterior.</Notice>
    <form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void generate()}} noValidate>
      <label className="text-sm font-bold">País receptor *<input className={input} value={form.country} onChange={e=>update("country",e.target.value)} maxLength={80}/></label>
      <label className="text-sm font-bold">Misión diplomática *<input className={input} value={form.mission} onChange={e=>update("mission",e.target.value)} maxLength={120}/></label>
      <label className="text-sm font-bold">Tipo de representación<select className={input} value={form.kind} onChange={e=>update("kind",e.target.value)}><option>Embajada</option><option>Consulado</option><option>Misión permanente</option><option>Oficina de enlace</option></select></label>
      <label className="text-sm font-bold">Vector de análisis<select className={input} value={form.criterion} onChange={e=>update("criterion",e.target.value)}>{criteria.map(item=><option key={item}>{item}</option>)}</select></label>
      <label className="text-sm font-bold">Periodo evaluado *<input type="month" className={input} value={form.period} onChange={e=>update("period",e.target.value)}/></label>
      <div className="sm:col-span-2"><Notice tone="pink"><strong>Aportación documentada con identidad protegida.</strong> La plataforma procura minimizar la exposición de datos, pero no garantiza anonimato absoluto. Evite incluir domicilios, información migratoria, identificaciones oficiales o datos sensibles innecesarios.</Notice></div>
      <label className="text-sm font-bold sm:col-span-2">Aportación documentada *<textarea className={input} rows={5} value={form.contribution} onChange={e=>update("contribution",e.target.value)} maxLength={3000}/><span className="mt-1 block text-xs font-normal text-slate-500">{form.contribution.length}/3000 · mínimo 80 caracteres</span></label>
      <label className="text-sm font-bold sm:col-span-2">Fuentes públicas *<textarea className={input} rows={3} value={form.sources} onChange={e=>update("sources",e.target.value)} placeholder="Una fuente por línea" maxLength={1500}/></label>
      <label className="text-sm font-bold sm:col-span-2">Observaciones opcionales<textarea className={input} rows={3} value={form.notes} onChange={e=>update("notes",e.target.value)} maxLength={1200}/></label>
      <label className="rounded-xl border border-dashed border-slate-300 p-4 text-sm font-bold sm:col-span-2">Evidencias demostrativas (PDF, PNG, JPG o TXT; máximo 5 MB)<input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.txt" className="mt-2 block w-full text-sm font-normal" onChange={e=>addFiles(e.target.files)}/><span className="mt-2 block text-xs font-normal text-slate-500">Los archivos no se han enviado ni almacenado en un servidor.</span></label>
      {evidence.length>0&&<ul className="space-y-2 sm:col-span-2">{evidence.map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-xs"><span><strong>{item.name}</strong> · {item.type} · {formatBytes(item.size)} · {item.addedAt} · Local</span><button type="button" onClick={()=>setEvidence(current=>current.filter(x=>x.id!==item.id))} className="font-bold text-[#B00061]">Eliminar</button></li>)}</ul>}
      {errors.length>0&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800 sm:col-span-2"><strong>Revise lo siguiente:</strong><ul className="mt-1 list-disc pl-5">{errors.map(error=><li key={error}>{error}</li>)}</ul></div>}
      <div className="flex flex-wrap gap-3 sm:col-span-2"><button className="rounded-xl bg-[#E4007C] px-5 py-3 text-sm font-black text-white shadow hover:bg-[#B00061]">Generar borrador de dictamen cívico</button><button type="button" onClick={clear} className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">Limpiar formulario</button></div>
    </form></Panel>
    {report&&<Panel title="Borrador de dictamen cívico" description="Documento local de apoyo · versión 1.0"><article className="space-y-4 print:block"><div className="grid gap-3 sm:grid-cols-3"><div><span className="text-xs font-bold text-slate-500">Folio</span><p className="font-mono text-sm">{report.folio}</p></div><div><span className="text-xs font-bold text-slate-500">Fecha</span><p className="text-sm">{new Date().toLocaleDateString("es-MX")}</p></div><div><span className="text-xs font-bold text-slate-500">Alcance</span><p className="text-sm">Evaluación ciudadana demostrativa</p></div></div><h3 className="font-black text-[#0A4E84]">Resumen ejecutivo</h3><p className="text-sm leading-6">La aportación analiza {form.criterion.toLowerCase()} en {form.mission}, {form.country}, durante {form.period}. Se incorporaron {evidence.length} evidencias locales y fuentes públicas declaradas.</p><div className="grid gap-4 sm:grid-cols-2"><div><h3 className="font-black">Fortalezas detectadas</h3><p className="text-sm text-slate-600">Aspectos documentados que requieren contraste por el comité revisor.</p></div><div><h3 className="font-black">Riesgos o brechas</h3><p className="text-sm text-slate-600">Información faltante, sesgos posibles y necesidad de verificación independiente.</p></div></div><h3 className="font-black">Recomendaciones</h3><p className="text-sm text-slate-600">Revisar las fuentes, solicitar contraste técnico y documentar la participación de la diáspora antes de cualquier actuación externa.</p><p className="break-all rounded-xl bg-slate-50 p-3 font-mono text-[10px]"><strong>Huella SHA-256 local:</strong> {report.hash}</p><Notice tone="amber">Borrador ciudadano sin carácter oficial, vinculante ni diplomático. Requiere revisión humana.</Notice><div className="flex flex-wrap gap-3 print:hidden"><button onClick={()=>window.print()} className="rounded-xl bg-[#0A4E84] px-4 py-2 text-sm font-bold text-white">Imprimir / guardar como PDF</button><button onClick={()=>setReport(null)} className="rounded-xl border px-4 py-2 text-sm font-bold">Volver a editar</button></div></article></Panel>}
    <span aria-live="polite" className="sr-only">{message}</span></div>;
}
