import type { DiasporaRepresentative, InternationalCase, SolidarityCampaign, TraceabilityRecord } from "./types";
export const representatives: DiasporaRepresentative[] = [
    { id: "rep-1", name: "Marina Solís (perfil ficticio)", role: "Representante Cívica de la Diáspora", country: "Estados Unidos", city: "Chicago", region: "Norteamérica", specialties: ["Derechos humanos", "Movilidad humana"], languages: ["Español", "Inglés"], experience: "12 años de trabajo comunitario demostrativo", collaboration: "Documentación y vinculación", biography: "Especialista ficticia en acompañamiento comunitario y acceso a derechos.", activities: "Talleres públicos y mesas de escucha (datos demostrativos).", status: "Trayectoria revisada", reviewDate: "18/07/2026", conflict: "Ninguno declarado en este ejemplo." },
    { id: "rep-2", name: "Diego Neri (perfil ficticio)", role: "Enlace Cívico Transnacional", country: "España", city: "Madrid", region: "Europa", specialties: ["Cooperación internacional", "Transparencia"], languages: ["Español", "Inglés", "Francés"], experience: "8 años de análisis demostrativo", collaboration: "Fuentes abiertas y cooperación", biography: "Perfil ficticio dedicado al análisis de políticas públicas comparadas.", activities: "Foros académicos demostrativos.", status: "Validado por Comité Ciudadano", reviewDate: "11/07/2026", conflict: "Colaboración académica declarada." },
    { id: "rep-3", name: "Ixchel Tun (perfil ficticio)", role: "Especialista Sectorial", country: "Canadá", city: "Toronto", region: "Norteamérica", specialties: ["Agua y territorio", "Pueblos indígenas"], languages: ["Español", "Inglés"], experience: "10 años de investigación demostrativa", collaboration: "Revisión técnica", biography: "Perfil ficticio con experiencia en documentación territorial.", activities: "Publicaciones y seminarios demostrativos.", status: "Perfil en evaluación", reviewDate: "Pendiente", conflict: "Sin información adicional." },
];
export const internationalCases: InternationalCase[] = [
    { id: "INT-30-2026-004", title: "Acceso comunitario al agua en zona fronteriza", summary: "Expediente demostrativo que organiza fuentes públicas y riesgos territoriales para revisión humana.", category: "Agua y territorio", region: "Norteamérica", status: "Revisión experta", priority: "Alta", committee: "Comité ciudadano de agua y territorio", mechanism: "Relatorías temáticas (referencia potencial)", pending: ["Completar matriz de fuentes", "Revisar consentimiento humano"], sources: ["Informe público local", "Marco convencional aplicable"], documents: ["Matriz de hechos v1.2", "Ficha de fuentes v1.1"], timeline: [{ date: "08/07/2026", event: "Integración documental" }, { date: "15/07/2026", event: "Revisión ciudadana" }, { date: "20/07/2026", event: "Turno a revisión experta" }] },
    { id: "INT-30-2026-007", title: "Protección de personas mexicanas en movilidad", summary: "Expediente demostrativo para clasificación, seguimiento y preparación documental.", category: "Movilidad humana", region: "Europa", status: "Integración documental", priority: "Preventiva", committee: "Comité ciudadano de movilidad", mechanism: "Mecanismos regionales por determinar", pending: ["Agregar cronología", "Identificar fuentes primarias"], sources: ["Datos públicos demostrativos"], documents: ["Ficha inicial v0.2"], timeline: [{ date: "19/07/2026", event: "Borrador creado" }] },
];
export const campaigns: SolidarityCampaign[] = [
    { id: "CAM-30-01", title: "Apoyo documental para defensa territorial (demostrativa)", cause: "Derechos ambientales", location: "México / diáspora", platform: "Proveedor externo por definir", owner: "Colectivo ciudadano ficticio", raised: 18400, goal: 50000, status: "Información pública revisada por Comité Ciudadano", reviewDate: "16/07/2026", reviewed: "Descripción, responsable declarado y documentos públicos.", unverified: "Destino final de recursos y cifras mostradas." },
];
export const traceRecords: TraceabilityRecord[] = [
    { folio: "TR-30-2026-019", caseName: "Acceso comunitario al agua", documentType: "Dossier ciudadano", version: "1.3", date: "20/07/2026", time: "14:32", hash: "a7f45243d8222ce4b9d27f37e2815a6e7a11fa772fd543257299d211a64310fd", status: "Revisión experta", committee: "Agua y territorio", actor: "Secretaría técnica ciudadana", action: "Nueva versión", notes: "Se incorporó matriz de fuentes." },
    { folio: "TR-30-2026-016", caseName: "Protección en movilidad", documentType: "Ficha de expediente", version: "0.2", date: "19/07/2026", time: "09:10", hash: "3d930bf7b6463707bc50dfde12e7f91bfcb019d428e5979e4492695f6d2bc8bf", status: "Integración documental", committee: "Movilidad humana", actor: "Enlace cívico", action: "Registro local", notes: "Datos demostrativos; revisión pendiente." },
];
